### ISSUE TITLE
Allow "[*]" expression

### ISSUE THREAD

**Issue by IntheDark** [soi013/FileRenamerDiff#8]
As [ch_group]] removes any single character in ch_group, we cant include something like [*].

Here's an example:
Movie [2021][English].mkv > Movie.mkv

If there is a way to delete anything inside "[" and "]" (those characters included) let me know, please.

Thanks.

**Comment by soi013** [comment]
Thank you for comment!
How about `\[.*\]` in Delete Texts?

**Comment by IntheDark** [comment]
Yes, that did the trick.
Thanks a lot.

**Comment by soi013** [comment]
I'm glad to hear that.
If you have any more questions, please feel free to ask me anytime.
